//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForDiplom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class diplomEntities2 : DbContext
    {
        public diplomEntities2()
            : base("name=diplomEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Изменения_состояний_партий> Изменения_состояний_партий { get; set; }
        public virtual DbSet<Коды_отходов> Коды_отходов { get; set; }
        public virtual DbSet<Контейнер> Контейнер { get; set; }
        public virtual DbSet<Партии_отходов> Партии_отходов { get; set; }
        public virtual DbSet<Собранные_отходы_клиентов> Собранные_отходы_клиентов { get; set; }
        public virtual DbSet<Состояния_партии_отходов> Состояния_партии_отходов { get; set; }
    }
}
