//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForDiplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Контейнер
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Контейнер()
        {
            this.Партии_отходов = new HashSet<Партии_отходов>();
        }
    
        public int Id_Контейнера { get; set; }
        public int Id_Типа_Контейнеров { get; set; }
        public string Номер_контейнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Партии_отходов> Партии_отходов { get; set; }
    }
}
