//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForDiplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Коды_отходов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Коды_отходов()
        {
            this.Собранные_отходы_клиентов = new HashSet<Собранные_отходы_клиентов>();
        }
    
        public int Id_Кода { get; set; }
        public string Код { get; set; }
        public int Количество { get; set; }
        public int Id_клиента { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Собранные_отходы_клиентов> Собранные_отходы_клиентов { get; set; }
    }
}
