//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForDiplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class КодыИдентификацииОтходов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public КодыИдентификацииОтходов()
        {
            this.ОтходыПоКоду = new HashSet<ОтходыПоКоду>();
        }
    
        public int IdКода { get; set; }
        public string Код { get; set; }
        public int IdКлиента { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОтходыПоКоду> ОтходыПоКоду { get; set; }
    }
}
