//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForDiplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОтходыПоКоду
    {
        public int IdОтходовПоКоду { get; set; }
        public int Вес { get; set; }
        public System.DateTime Дата { get; set; }
        public Nullable<int> IdАккаунта { get; set; }
        public int IdКода { get; set; }
        public Nullable<int> IdПартииОтходов { get; set; }
    
        public virtual КодыИдентификацииОтходов КодыИдентификацииОтходов { get; set; }
        public virtual ПартииОтходов ПартииОтходов { get; set; }
    }
}
