//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForDiplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партии_отходов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Партии_отходов()
        {
            this.Изменения_состояний_партий = new HashSet<Изменения_состояний_партий>();
        }
    
        public int Id_партии_отходов { get; set; }
        public string Номер_партии_отходов { get; set; }
        public System.DateTime дата_формирования { get; set; }
        public Nullable<decimal> Вес { get; set; }
        public int Id_Типа { get; set; }
        public Nullable<int> Id_Контейнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Изменения_состояний_партий> Изменения_состояний_партий { get; set; }
        public virtual Контейнер Контейнер { get; set; }
    }
}
