//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForDiplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПартииОтходов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПартииОтходов()
        {
            this.ОтходыПоКоду = new HashSet<ОтходыПоКоду>();
            this.ПеремещенияОтходовВНовыйКонтейнер = new HashSet<ПеремещенияОтходовВНовыйКонтейнер>();
        }
    
        public int IdПартииОтходов { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
        public Nullable<int> Вес { get; set; }
        public int IdТипа { get; set; }
        public int IdКонтейнера { get; set; }
    
        public virtual Контейнеры Контейнеры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОтходыПоКоду> ОтходыПоКоду { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПеремещенияОтходовВНовыйКонтейнер> ПеремещенияОтходовВНовыйКонтейнер { get; set; }
    }
}
