//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForDiplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПеремещенияКонтейнераВНовоеПомещение
    {
        public int IdКонтейнера { get; set; }
        public int IdПомещения { get; set; }
        public System.DateTime Дата { get; set; }
        public int IdЗаписи { get; set; }
    
        public virtual Контейнеры Контейнеры { get; set; }
        public virtual Помещения Помещения { get; set; }
    }
}
