//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForDiplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Помещения
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Помещения()
        {
            this.Контейнеры = new HashSet<Контейнеры>();
            this.ПеремещенияКонтейнераВНовоеПомещение = new HashSet<ПеремещенияКонтейнераВНовоеПомещение>();
        }
    
        public int IdПомещения { get; set; }
        public string НомерНаименование { get; set; }
        public int IdПолигона { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Контейнеры> Контейнеры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПеремещенияКонтейнераВНовоеПомещение> ПеремещенияКонтейнераВНовоеПомещение { get; set; }
        public virtual Полигоны Полигоны { get; set; }
    }
}
