//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForDiplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Собранные_отходы_клиентов
    {
        public int Id_Отходов_по_коду { get; set; }
        public decimal Вес { get; set; }
        public int Id_Кода { get; set; }
        public int Id_Типа { get; set; }
    
        public virtual Коды_отходов Коды_отходов { get; set; }
    }
}
